name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.10.4

      - name: Setup StyLua
        uses: taiki-e/install-action@v2
        with:
          tool: stylua

      - name: Format Lua files
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        run: make format

      - name: Commit formatted Lua files
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: style: format lua files
          file_pattern: lua/**/*.lua scripts/**/*.lua

      - name: Run checks
        run: make check
